In [1]:
import pandas as pd
import matplotlib.pyplot as plt

In [2]:
from google.colab import files

# upload do arquivo
uploaded = files.upload()

Saving data_v2.csv to data_v2.csv

In [3]:
data = pd.read_csv('data_v2.csv')

Removendo todas as linhas que tenham ao menos um campo nulo

In [5]:
data = data.dropna()
data

,valor,cep,cidade,bairro,zona,logradouro,categoria,area,qtde_quartos,qtde_vagas,qtde_banheiros
0,180000.0,69054060.0,Manaus,Parque 10 de Novembro,Centro-Sul,Rua 5,Casas,180.0,2.0,1.0,1.0
2,140000.0,69095000.0,Manaus,Cidade Nova,Norte,Avenida Noel Nutels - de 851/852 a 2399/2400,Casas,50.0,3.0,1.0,2.0
3,380000.0,69053030.0,Manaus,Nossa Senhora das Graças,Centro-Sul,Avenida Rio Madeira,Apartamentos,85.0,3.0,1.0,2.0
4,450000.0,69057050.0,Manaus,Adrianópolis,Centro-Sul,Avenida Ephigênio Salles,Apartamentos,120.0,3.0,2.0,2.0
5,90000.0,69038561.0,Manaus,Lírio do Vale,Oeste,Rua Ilha Oregon,Apartamentos,42.0,2.0,1.0,1.0
...,...,...,...,...,...,...,...,...,...,...,...
4499,650000.0,69037000.0,Manaus,Ponta Negra,Oeste,Avenida Coronel Teixeira,Casas,720.0,2.0,5.0,2.0
4500,40000.0,69037107.0,Manaus,Ponta Negra,Oeste,Rua Thales Loureiro,Apartamentos,60.0,3.0,2.0,2.0
4501,2000000.0,69037225.0,Manaus,Ponta Negra,Oeste,Avenida José Augusto Loureiro,Casas,404.0,5.0,4.0,5.0
4502,160368.0,69058000.0,Manaus,Flores,Centro-Sul,Conjunto Anavilhanas,Casas,80.0,2.0,2.0,2.0
4503,1600029.0,69037144.0,Manaus,Ponta Negra,Oeste,Avenida Frederico Baird,Casas,294.0,4.0,5.0,5.0

Removendo colunas que não vamos usar

In [11]:
data = data.drop(["cep", "cidade", "logradouro"], axis=1)

Obtendo os índices das linhas que contém dados inválidos (considerando as regras que estipulamos na aula) e removendo esses índices do dataset.

In [12]:
invalid_rows_index = data[(data['area'] < 20) | (data['valor'] < 40000)].index
data = data.drop(invalid_rows_index)
data

,valor,bairro,zona,categoria,area,qtde_quartos,qtde_vagas,qtde_banheiros
0,180000.0,Parque 10 de Novembro,Centro-Sul,Casas,180.0,2.0,1.0,1.0
2,140000.0,Cidade Nova,Norte,Casas,50.0,3.0,1.0,2.0
3,380000.0,Nossa Senhora das Graças,Centro-Sul,Apartamentos,85.0,3.0,1.0,2.0
4,450000.0,Adrianópolis,Centro-Sul,Apartamentos,120.0,3.0,2.0,2.0
5,90000.0,Lírio do Vale,Oeste,Apartamentos,42.0,2.0,1.0,1.0
...,...,...,...,...,...,...,...,...
4499,650000.0,Ponta Negra,Oeste,Casas,720.0,2.0,5.0,2.0
4500,40000.0,Ponta Negra,Oeste,Apartamentos,60.0,3.0,2.0,2.0
4501,2000000.0,Ponta Negra,Oeste,Casas,404.0,5.0,4.0,5.0
4502,160368.0,Flores,Centro-Sul,Casas,80.0,2.0,2.0,2.0
4503,1600029.0,Ponta Negra,Oeste,Casas,294.0,4.0,5.0,5.0

Gerando um novo arquivo com os dados filtrados: data_v3.csv

In [13]:
data.to_csv('data_v3.csv')

Dados para o cálculo da amostra estratificada:

In [14]:
data['zona'].value_counts()

Centro-Sul      1237
Oeste           1093
Norte            620
Centro-Oeste     337
Sul              145
Leste             89
Name: zona, dtype: int64

Percentuais de cada zona para validar a amostra:

In [16]:
data['zona'].value_counts(normalize=True) * 100

Centro-Sul      35.132065
Oeste           31.042318
Norte           17.608634
Centro-Oeste     9.571145
Sul              4.118148
Leste            2.527691
Name: zona, dtype: float64

Para uma amostra de $n=400$, os valores $n_h$ para cada classe são:

| Zona         | $n_h$ |
|--------------|-------|
| Centro-Sul   |       |
| Oeste        |       |
| Norte        |       |
| Centro-Oeste |       |
| Leste        |       |

Obtendo as amostras de cada estrato (zona) e compondo a amostra final

In [36]:
# precisa adicionar os valores de nh aqui
estrato_1 = data[data['zona'] == 'Centro-Sul'].sample(10, random_state=42)
estrato_2 = data[data['zona'] == 'Oeste'].sample(10, random_state=42)
estrato_3 = data[data['zona'] == 'Norte'].sample(10, random_state=42)
estrato_4 = data[data['zona'] == 'Centro-Oeste'].sample(10, random_state=42)
estrato_5 = data[data['zona'] == 'Leste'].sample(10, random_state=42)

In [38]:
amostra = pd.concat([estrato_1, estrato_2, estrato_3, estrato_4, estrato_5], ignore_index=True)
amostra

,valor,bairro,zona,categoria,area,qtde_quartos,qtde_vagas,qtde_banheiros
0,260199.0,Parque 10 de Novembro,Centro-Sul,Casas,70.0,2.0,2.0,2.0
1,630000.0,Flores,Centro-Sul,Casas,144.0,3.0,2.0,2.0
2,540000.0,Flores,Centro-Sul,Apartamentos,90.0,3.0,2.0,1.0
3,298000.0,Parque 10 de Novembro,Centro-Sul,Casas,80.0,2.0,2.0,2.0
4,245000.0,Parque 10 de Novembro,Centro-Sul,Casas,350.0,3.0,3.0,2.0
5,199000.0,Nossa Senhora das Graças,Centro-Sul,Casas,55.0,2.0,1.0,1.0
6,540000.0,Flores,Centro-Sul,Apartamentos,90.0,3.0,2.0,2.0
7,199000.0,Aleixo,Centro-Sul,Apartamentos,91.0,2.0,1.0,2.0
8,4500000.0,Aleixo,Centro-Sul,Casas,884.0,5.0,5.0,5.0
9,525000.0,Adrianópolis,Centro-Sul,Apartamentos,117.0,3.0,2.0,2.0
10,400000.0,Nova Esperança,Oeste,Casas,346.0,5.0,4.0,5.0
11,550000.0,Tarumã,Oeste,Casas,380.0,3.0,2.0,4.0
12,600000.0,Vila da Prata,Oeste,Casas,310.0,4.0,4.0,5.0
13,2900000.0,Ponta Negra,Oeste,Casas,450.0,5.0,5.0,2.0
14,520000.0,Ponta Negra,Oeste,Apartamentos,91.0,3.0,2.0,2.0
15,988003.0,Ponta Negra,Oeste,Apartamentos,146.0,3.0,2.0,3.0
16,1500000.0,Tarumã,Oeste,Casas,198.0,3.0,4.0,4.0
17,150000.0,São Jorge,Oeste,Casas,250.0,3.0,2.0,2.0
18,160000.0,Lírio do Vale,Oeste,Apartamentos,42.0,2.0,1.0,1.0
19,1500000.0,Ponta Negra,Oeste,Casas,190.0,3.0,4.0,4.0
20,700000.0,Novo Israel,Norte,Casas,170.0,4.0,4.0,1.0
21,85000.0,Nova Cidade,Norte,Casas,90.0,2.0,2.0,1.0
22,240000.0,Colônia Santo Antônio,Norte,Apartamentos,75.0,3.0,1.0,2.0
23,65000.0,Novo Israel,Norte,Casas,8588.0,2.0,2.0,1.0
24,240000.0,Colônia Santo Antônio,Norte,Apartamentos,75.0,3.0,1.0,1.0
25,160000.0,Lago Azul,Norte,Apartamentos,80.0,2.0,1.0,1.0
26,140000.0,Nova Cidade,Norte,Casas,150.0,2.0,5.0,3.0
27,280000.0,Cidade Nova,Norte,Casas,173.0,4.0,2.0,3.0
28,850000.0,Colônia Terra Nova,Norte,Casas,218.0,3.0,4.0,4.0
29,240000.0,Cidade Nova,Norte,Casas,300.0,2.0,3.0,2.0
30,680000.0,Dom Pedro I,Centro-Oeste,Apartamentos,96.0,3.0,2.0,3.0
31,249000.0,Dom Pedro I,Centro-Oeste,Casas,122.0,3.0,2.0,1.0
32,179685.0,Planalto,Centro-Oeste,Apartamentos,38.0,2.0,1.0,1.0
33,470000.0,Dom Pedro I,Centro-Oeste,Apartamentos,84.0,3.0,1.0,2.0
34,247600.0,Planalto,Centro-Oeste,Apartamentos,51.0,2.0,1.0,2.0
35,315000.0,Alvorada,Centro-Oeste,Apartamentos,59.0,2.0,1.0,1.0
36,650005.0,Dom Pedro I,Centro-Oeste,Casas,600.0,5.0,3.0,5.0
37,690000.0,Redenção,Centro-Oeste,Casas,450.0,5.0,4.0,5.0
38,530000.0,Dom Pedro I,Centro-Oeste,Apartamentos,84.0,3.0,3.0,3.0
39,499997.0,Dom Pedro I,Centro-Oeste,Casas,200.0,4.0,4.0,3.0
40,225000.0,São José Operário,Leste,Casas,200.0,3.0,2.0,4.0
41,120000.0,Jorge Teixeira,Leste,Casas,70.0,3.0,2.0,2.0
42,350000.0,Coroado,Leste,Casas,300.0,4.0,3.0,5.0
43,65000.0,Gilberto Mestrinho,Leste,Apartamentos,65.0,2.0,1.0,1.0
44,185100.0,Zumbi dos Palmares,Leste,Apartamentos,43.0,2.0,1.0,1.0
45,180000.0,São José Operário,Leste,Apartamentos,55.0,2.0,1.0,1.0
46,2750000.0,Puraquequara,Leste,Apartamentos,1500.0,5.0,5.0,5.0
47,49999.0,Jorge Teixeira,Leste,Casas,20.0,1.0,1.0,1.0
48,150010.0,Jorge Teixeira,Leste,Casas,80.0,3.0,1.0,2.0
49,159000.0,Zumbi dos Palmares,Leste,Apartamentos,43.0,2.0,1.0,1.0

In [39]:
amostra.to_csv('data_amostra.csv')